export const CHANGE_SIDEBAR_STATE = 'CHANGE_SIDEBAR_STATE'

export const BADGE_LIST = 'BADGE_LIST'
export const BADGE_SAVE = 'BADGE_SAVE'
export const BADGE_EDIT = 'BADGE_EDIT'

export const VIDEOS_LIST = 'VIDEOS_LIST'
export const VIDEOS_LIST_ERROR = 'VIDEOS_LIST_ERROR'
export const VIDEOS_LIST_SUCCESS = 'VIDEOS_LIST_SUCCESS'
